name: CI/CD for Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run tests
        run: |
          if [ -d tests ]; then pytest; else echo 'No tests directory'; fi

      - name: Build Docker image
        run: |
          docker build -t flask-app-test .

      - name: Run Docker container (test startup)
        run: |
          docker run --rm -d -p 5003:5003 --name flask-app-test-container flask-app-test
          sleep 10
          docker ps -a
          docker logs flask-app-test-container || true
          docker stop flask-app-test-container

